import {
  longSentences,
  midPhraseBreaks,
  uniformParagraphs,
  uniformSentences,
  wallOfText,
} from "./shape.js";

/**
 * A rule is a regular expression plus a message,
 * or a check function that reads all lines at once.
 *
 * scope controls where the rule runs:
 *   prose      → markdown and text files
 *   comments   → comments inside code files
 *   text       → both of the above (the default)
 *   everywhere → every line of every file
 *
 * Patterns must have the g flag.
 *
 * A check function gets the segments of one file and the scope
 * they came from. It returns { line, column, text } per finding.
 */

function words(list) {
  return list.map(escape).join("|");
}

function anyOf(list) {
  return new RegExp(String.raw`\b(?:${words(list)})\b`, "gi");
}

function escape(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Three shapes of one move: naming the thing it is not.
 *
 *   not just X, but Y
 *   it is not X, it is Y
 *   X, not Y: the rest
 *
 * The third wants a label colon, so "a, not https://b" stays out. It also
 * stays on one line, so a wrapped block comment cannot join two sentences
 * into a match.
 */
const CONTRAST_CLICHES = [
  String.raw`\bnot (?:just|only|merely|simply) [^.\n]{1,60}?,? but(?: also)?\b`,
  String.raw`\bit'?s not (?:just |about )?[^.\n]{1,40}?[,;] it'?s\b`,
  String.raw`[^\s,:][^,:\n]{0,29},[ \t]+not[ \t]+[^,:\n]{1,30}:(?=\s|$)`,
];

const BANNED_WORDS = [
  "genuinely",
  "fails loudly",
  "fails quietly",
  "spearheaded",
  "exactly the crutch",
  "crutch",
  "load bearing",
  "load-bearing",
  "carrying",
];

const FILLER_WORDS = ["simply", "seamlessly", "seamless", "robust"];

const LLM_VOCABULARY = [
  "delve",
  "delves",
  "delving",
  "tapestry",
  "streamline",
  "streamlines",
  "streamlined",
  "cutting-edge",
  "game-changer",
  "game changer",
  "at its core",
  "deep dive",
  "dive into",
  "let's dive",
  "multifaceted",
  "pivotal",
  "crucial",
  "myriad",
  "plethora",
  "foster",
  "fosters",
  "meticulous",
  "meticulously",
  "a testament to",
  "in today's",
  "fast-paced",
  "ever-evolving",
  "effortlessly",
  "supercharge",
  "state-of-the-art",
  "battle-tested",
  "production-ready",
  "blazing fast",
  "blazingly fast",
  "lightning-fast",
  "lightning fast",
  "elevate your",
  "empower",
  "empowers",
  "empowering",
  "navigate the complexities",
  "unlock the",
];

const CHAT_OPENERS = [
  "great question",
  "good question",
  "certainly",
  "absolutely",
  "sure thing",
  "sure",
  "of course",
  "let me",
  "i will",
  "i'll",
  "looking at your",
  "here's a",
  "here is a",
  "i'd be happy to",
  "i would be happy to",
];

const CHAT_CLOSERS = [
  "let me know if",
  "hope this helps",
  "hope that helps",
  "feel free to",
  "happy to help",
  "don't hesitate to",
  "do not hesitate to",
  "if you have any questions",
  "if there is anything else",
  "if there's anything else",
  "anything else i can",
];

const AI_DISCLOSURES = [
  "as an ai",
  "as a language model",
  "as a large language model",
  "i apologize for the confusion",
  "i apologize for any confusion",
  "i don't have access to",
  "i cannot browse",
  "my knowledge cutoff",
  "my training data",
];

// Talk that only makes sense while the change is under review.
// Once merged, nobody reading the code knows what "the old way" or "this PR" was.
const PR_TALK = [
  // The change itself
  "as requested",
  "as discussed",
  "per the discussion",
  "per our discussion",
  "per the review",
  "per review",
  "per feedback",
  "based on feedback",
  "review feedback",
  "review comment",
  "review comments",
  "addressing feedback",
  "addresses feedback",
  "addressed feedback",
  "requested changes",
  "code review",
  "reviewer",
  "reviewers",
  "this pr",
  "this mr",
  "pr description",
  "pull request",
  "merge request",
  "this commit",
  "this diff",
  "this change",
  "this refactor",
  "the refactor",
  "this migration",
  "this upgrade",
  "the upgrade",
  "after upgrading",
  "before upgrading",
  "since upgrading",
  "version bump",
  "this bump",
  "cherry-picked",
  "cherry picked",
  "backported",
  "rebased",
  "merge conflict",
  "merge conflicts",
  "work in progress",
  "wip",
  // How the code used to be
  "no longer",
  "used to be",
  "used to use",
  "used to return",
  "the old implementation",
  "the old version",
  "the old code",
  "the old approach",
  "the old way",
  "updated to",
  "changed to",
  "instead of the old",
  "instead of the previous",
  "we removed",
  "we replaced",
  "we migrated",
  "we switched",
  "now uses",
  "now returns",
  "now handles",
  "now lives",
  "moved to",
  "never worked",
  "wasn't working",
  "was not working",
  "weren't working",
  "were not working",
  "didn't work before",
  "did not work before",
  "stopped working",
  "was failing",
  "were failing",
  "started failing",
  "kept failing",
  "on the main branch",
  "on the master branch",
  "compared to main",
  "compared to master",
  // Claims that nothing changed
  "no behavior change",
  "no behaviour change",
  "no functional change",
  "no functional changes",
  "no-op change",
  "behavior is unchanged",
  "behaviour is unchanged",
  "behavior unchanged",
  "behaviour unchanged",
  "no change in behavior",
  "no change in behaviour",
  "same as before",
  "same behavior as before",
  "same behaviour as before",
  "behaves as before",
  "behaves the same",
  "works the same",
  "functionally equivalent",
  "functionally identical",
  "preserves behavior",
  "preserves behaviour",
  "preserve behavior",
  "preserve behaviour",
  "preserves existing behavior",
  "preserves existing behaviour",
  "existing behavior",
  "existing behaviour",
  "unchanged from",
  // Leaving things as they were
  "keeping it off",
  "keeping it on",
  "keeping this off",
  "keeping this on",
  "keeping it disabled",
  "keeping it enabled",
  "keeping this disabled",
  "keeping this enabled",
  "keep it off",
  "keep this off",
  "kept as is",
  "kept as-is",
  "left as is",
  "left as-is",
  "leave as is",
  "leave as-is",
  "leaving as is",
  "leaving as-is",
  "left in place",
  "left untouched",
  "left alone",
  "leaving this alone",
  "not touching",
  "didn't touch",
  "did not touch",
  // Scope and follow-ups
  "for now",
  "out of scope",
  "scope of this",
  "follow-up pr",
  "follow up pr",
  "in a follow-up",
  "in a follow up",
  "as a follow-up",
  "as a follow up",
  "separate pr",
  "later pr",
  "future pr",
  "another pr",
  "next pr",
  "will be removed",
  "can be removed",
  "to be removed",
  "should be removed",
  "safe to remove",
  "safe to delete",
  "can be deleted",
  "will be deleted",
  "remove this once",
  "remove this after",
  "remove this when",
  "delete this once",
  "delete this after",
  "clean up later",
  "cleanup later",
  "clean this up later",
  "will clean up",
  "will be cleaned up",
  "quick fix",
  "quick hack",
  "quick and dirty",
  "band-aid",
  "bandaid",
  "band aid",
  "stopgap",
  "stop-gap",
  "stop gap",
  "hotfix",
  "hot fix",
  // The author talking about their own process
  "tested locally",
  "verified locally",
  "confirmed locally",
  "works locally",
  "tested with",
  "tested on",
  "tested against",
  "verified with",
  "confirmed with",
  "ci passes",
  "passes ci",
  "ci is green",
  "ci was failing",
  "ci fails",
  "ci failed",
  "i tested",
  "i verified",
  "i checked",
  "i confirmed",
  "i tried",
  "i went with",
  "i chose",
  "i opted",
  "i decided",
  "i ended up",
  "i left",
  "i kept",
  "i removed",
  "i replaced",
  "i added",
  "i moved",
  "i renamed",
  "i changed",
  "i updated",
  "i bumped",
  "i couldn't",
  "i could not",
  "i'm not sure",
  "i am not sure",
  "not sure if",
  "not sure why",
  "not sure whether",
  "we tested",
  "we verified",
  "we confirmed",
  "we decided",
  "we went with",
  "we opted",
  "we couldn't",
  "we could not",
];

// PR talk only when it opens a sentence. "used previously" is fine.
const PR_OPENERS = ["previously", "formerly", "originally"];

const DRAMATIC_VERBS = [
  "blow up",
  "blows up",
  "blowing up",
  "blew up",
  "die with",
  "dies with",
  "died with",
  "fall over",
  "falls over",
  "fell over",
  "choke on",
  "chokes on",
  "choked on",
  "trip over",
  "trips over",
  "tripped over",
  "bites us",
  "bites you",
  "bit us",
  "explode",
  "explodes",
  "exploded",
  "barf",
  "barfs",
];

const ERROR_OPENERS = [
  "Cannot",
  "Could not",
  "Couldn't",
  "Unable to",
  "Failed to",
  "Unexpected",
  "Invalid",
  "Expected",
  "Missing",
  "Uncaught",
  "Assertion Failed",
  "Maximum call stack",
];

const ASIDE_OPENERS = ["and", "but", "though", "although", "plus", "as well as", "not to mention"];

const WHAT_COMMENT_STARTS = [
  "this function",
  "this method",
  "this class",
  "this component",
  "this helper",
  "this hook",
  "this file",
  "this module",
  "this variable",
  "this constant",
  "this line",
  "loop over",
  "loop through",
  "iterate over",
  "iterate through",
  "check if",
  "checks if",
  "increment",
  "decrement",
  "set the",
  "sets the",
  "get the",
  "gets the",
  "create a new",
  "creates a new",
  "initialize the",
  "initializes the",
  "import the",
  "imports the",
  "define the",
  "defines the",
  "call the",
  "calls the",
  "declare",
];

// A comment starts after its marker, so the rule skips the marker first.
const COMMENT_START = String.raw`^\s*(?:\/\/+|#+|\*+|\/\*+|<!--|--|;+|%+|"""|''')?\s*`;

// The start of a comment or of a sentence, as a lookbehind.
const SENTENCE_START = String.raw`(?<=${COMMENT_START}|[.!?:;]\s+)`;

export const rules = [
  {
    id: "banned-word",
    message: "Banned word",
    pattern: anyOf(BANNED_WORDS),
  },
  {
    id: "em-dash",
    message: "Em dash. Use a comma, a colon, or a new sentence",
    pattern: /\u2014/g,
    scope: "comments",
  },
  {
    id: "bold-list-item",
    message: "List item with a bold label followed by plain text",
    pattern: /^\s*(?:[-*+]|\d+[.)])\s+(?:\*\*[^*\n]{1,80}\*\*|__[^_\n]{1,80}__):?(?=\s+[^\s*_])/gm,
    scope: "prose",
  },
  {
    id: "filler-word",
    message: "Filler. Delete it or replace it",
    pattern: anyOf(FILLER_WORDS),
  },
  {
    id: "llm-vocabulary",
    message: "LLM vocabulary",
    pattern: anyOf(LLM_VOCABULARY),
  },
  {
    id: "chat-opener",
    message: "Chat opener. Start with the answer",
    pattern: new RegExp(
      String.raw`${COMMENT_START}(?:[-*+]\s+)?(?:${words(CHAT_OPENERS)})\b[!,:]?`,
      "gmi",
    ),
  },
  {
    id: "chat-closer",
    message: "Chat closer. Stop when the content stops",
    pattern: anyOf(CHAT_CLOSERS),
  },
  {
    id: "ai-disclosure",
    message: "Text written from the point of view of a chat assistant",
    pattern: anyOf(AI_DISCLOSURES),
  },
  {
    id: "contrast-cliche",
    message: "Contrast cliche. State the thing directly",
    pattern: new RegExp(CONTRAST_CLICHES.join("|"), "gi"),
  },
  {
    id: "rhetorical-question",
    message: "Rhetorical question followed by its answer",
    pattern:
      /(?:\bwhy\? because\b|\bthe (?:result|catch|problem|solution|answer|best part|good news|bottom line|difference)\?)/gi,
    scope: "prose",
  },
  {
    id: "emoji-list",
    message: "List item that starts with an emoji",
    pattern:
      /^\s*(?:[-*+]|\d+[.)])\s+(?:\p{Emoji_Presentation}|\p{Extended_Pictographic}\uFE0F)/gmu,
    scope: "prose",
  },
  {
    id: "no-short-term-relevance",
    aliases: ["diff-comment"],
    message: "Comment only makes sense while the change is under review. Say it in the PR",
    pattern: new RegExp(
      String.raw`\b(?:${words(PR_TALK)})\b|${SENTENCE_START}(?:${words(PR_OPENERS)})\b`,
      "gmi",
    ),
    scope: "comments",
  },
  {
    id: "quoted-error",
    message:
      "Comment quotes an error message. Say what breaks and why, not what the terminal printed",
    pattern: new RegExp(
      String.raw`["\u201C](?:(?:${words(ERROR_OPENERS)})\b|\w+Error:|\w+ is not (?:a function|defined|iterable)\b)[^"\u201D\n]*["\u201D]?`,
      "g",
    ),
    scope: "comments",
  },
  {
    id: "dramatic-verb",
    message: "Dramatic failure verb. Say what happens: throws, hangs, returns null",
    pattern: anyOf(DRAMATIC_VERBS),
  },
  {
    id: "parenthetical-aside",
    message: "Parenthetical aside. Make it a sentence, or delete it",
    pattern: new RegExp(String.raw`\((?:${words(ASIDE_OPENERS)})\b[^()\n]*\)?`, "gi"),
  },
  {
    id: "what-comment",
    message: "Comment narrates what the code does. Say why, or delete it",
    pattern: new RegExp(String.raw`${COMMENT_START}(?:${words(WHAT_COMMENT_STARTS)})\b`, "gmi"),
    scope: "comments",
  },
  {
    id: "mid-phrase-break",
    message: "Line break in the middle of a phrase. Break where there is a pause",
    check: midPhraseBreaks,
  },
  {
    id: "long-sentence",
    message: "Long sentence. One idea per sentence",
    check: longSentences,
  },
  {
    id: "wall-of-text",
    message: "Wall of text. Split the paragraph",
    check: wallOfText,
  },
  {
    id: "uniform-paragraphs",
    message: "Consecutive paragraphs of the same length",
    check: uniformParagraphs,
    scope: "prose",
  },
  {
    id: "uniform-sentences",
    message: "Sentences of the same length. Vary the rhythm",
    check: uniformSentences,
  },
];
